spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#以下是默认转发规则
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

zuul:
  retryable: true
  
# 有默认值，不需要配置 
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1